import React, { useState } from 'react';
import CoursePageLayout from '../../components/CoursePageLayout';
import { Sparkles, Code, BookOpen, Lightbulb } from 'lucide-react';

const GenAiCoursePage = () => {
    const [activeTopicIndex, setActiveTopicIndex] = useState(0);

    const courseData = [
        {
            id: 'genai-intro',
            title: 'GenAI Intro',
            definition: 'Generative AI refers to deep-learning models that can generate high-quality text, images, and other content based on the data they were trained on.',
            example: 'ChatGPT generating a poem.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        Generative AI models learn the patterns and structure of their input training data and then generate new data that has similar characteristics.
                    </p>
                </>
            ),
            codeSnippet: null
        },
        {
            id: 'genai-llms',
            title: 'GenAI LLMs',
            definition: 'Large Language Models (LLMs) are a type of AI algorithm that uses deep learning techniques and vastly large data sets to understand, summarize, generate and predict new content.',
            example: 'GPT-4, Claude 3, Gemini.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        LLMs are trained on massive amounts of text data to learn the statistical relationships between words and phrases.
                    </p>
                </>
            ),
            codeSnippet: null
        },
        {
            id: 'genai-prompt-engineering',
            title: 'GenAI Prompt Engineering',
            definition: 'Prompt engineering is the process of structuring text that can be interpreted and understood by a generative AI model.',
            example: 'Writing specific instructions to get the desired output.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        A prompt is natural language text describing the task that an AI should perform.
                    </p>
                </>
            ),
            codeSnippet: `Act as a senior software engineer. Explain the concept of recursion to a 5-year-old.`
        },
        {
            id: 'genai-chatgpt',
            title: 'GenAI ChatGPT',
            definition: 'ChatGPT is an AI chatbot developed by OpenAI. It is built on top of OpenAI\'s GPT-3.5 and GPT-4 families of large language models.',
            example: 'Using ChatGPT to draft an email.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        ChatGPT interacts in a conversational way. The dialogue format makes it possible for ChatGPT to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.
                    </p>
                </>
            ),
            codeSnippet: null
        },
        {
            id: 'genai-image-generation',
            title: 'GenAI Image Generation',
            definition: 'AI image generators create images from text descriptions.',
            example: 'Midjourney, DALL-E 3, Stable Diffusion.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        These models are trained on billions of image-text pairs to understand the relationship between visual concepts and language.
                    </p>
                </>
            ),
            codeSnippet: null
        },
        {
            id: 'genai-code-generation',
            title: 'GenAI Code Generation',
            definition: 'Generative AI can be used to write code, debug code, and explain code.',
            example: 'GitHub Copilot suggesting code completions.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        AI coding assistants can help developers work faster by automating repetitive tasks and providing suggestions.
                    </p>
                </>
            ),
            codeSnippet: `# Generated by AI
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib = [0, 1]
        for i in range(2, n):
            fib.append(fib[i-1] + fib[i-2])
        return fib`
        },
        {
            id: 'genai-ethics',
            title: 'GenAI Ethics',
            definition: 'Ethical considerations in Generative AI include copyright, deepfakes, bias, and misinformation.',
            example: 'Deepfake videos of public figures.',
            content: (
                <>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">
                        It is important to use Generative AI responsibly and be aware of its limitations and potential risks.
                    </p>
                </>
            ),
            codeSnippet: null
        }
    ];

    const topics = courseData.map(topic => topic.title);
    const activeTopic = courseData[activeTopicIndex];

    const CodeBlock = ({ code, lang = 'python' }: { code: string, lang?: string }) => (
        <div className="bg-[#1e1e1e] text-gray-200 p-6 rounded-2xl font-mono text-sm mb-6 overflow-x-auto shadow-xl border border-gray-800">
            <div className="flex items-center space-x-2 mb-4 border-b border-gray-700 pb-4">
                <div className="w-3 h-3 rounded-full bg-red-500"></div>
                <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                <div className="w-3 h-3 rounded-full bg-green-500"></div>
                <span className="ml-4 text-xs text-gray-500 font-sans">main.py</span>
            </div>
            <pre className="leading-relaxed text-pink-300">{code}</pre>
        </div>
    );

    return (
        <CoursePageLayout
            title="Generative AI Tutorial"
            description="Generative AI is a type of artificial intelligence technology that can produce various types of content, including text, imagery, audio and synthetic data."
            topics={topics}
            icon={Sparkles}
            colorClass="pink"
            activeTopicIndex={activeTopicIndex}
            onTopicClick={setActiveTopicIndex}
        >
            <div className="space-y-8">
                {/* Definition Section */}
                <div className="bg-pink-50 dark:bg-pink-900/10 border-l-4 border-pink-600 p-6 rounded-r-xl">
                    <h3 className="text-lg font-bold text-pink-800 dark:text-pink-300 mb-2 flex items-center">
                        <BookOpen className="w-5 h-5 mr-2" />
                        Definition
                    </h3>
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                        {activeTopic.definition}
                    </p>
                </div>

                {/* Real-time Example Section */}
                <div className="bg-yellow-50 dark:bg-yellow-900/10 border-l-4 border-yellow-600 p-6 rounded-r-xl">
                    <h3 className="text-lg font-bold text-yellow-800 dark:text-yellow-300 mb-2 flex items-center">
                        <Lightbulb className="w-5 h-5 mr-2" />
                        Real-time Example
                    </h3>
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                        {activeTopic.example}
                    </p>
                </div>

                {/* Main Content & Code */}
                <div className="prose dark:prose-invert max-w-none">
                    {activeTopic.content}

                    {activeTopic.codeSnippet && (
                        <div className="mt-8">
                            <h3 className="text-xl font-bold mb-4 flex items-center text-gray-800 dark:text-white">
                                <Code className="w-6 h-6 mr-2 text-pink-600" />
                                Code Example
                            </h3>
                            <CodeBlock code={activeTopic.codeSnippet} />
                        </div>
                    )}
                </div>
            </div>
        </CoursePageLayout>
    );
};

export default GenAiCoursePage;
